### ISSUE TITLE
Hide the final result message as well?

### ISSUE THREAD

**Issue by Silvestrae** [malde/blind-death-saves#2]
This is a great little module that really makes my players stress when theyre rolling death saves. They love the suspense.
After 3 successes or failures have been made however, the output to chat shows everyone the result even though there's no way for their characters to know that result.

Is there a way to also hide that chat card that says when an actor has stabilised or died so that the players have to check the body to know the result?

**Comment by malde** [comment]
Ran into that situation myself a few times. I with you, just a bit tight on time.
But I'll look into it, should be possible I think.

**Comment by malde** [comment]
Took me some time to get to it, but managed to fix it for the next version (which will not longer support dnd5e system 2.4 though).
