### ISSUE TITLE
Argon Combat Hud Integration

### ISSUE THREAD

**Issue by FredXVI** [malde/blind-death-saves#3]
Hello, I am having an issue and was wondering if you could help.
I like to use the module: Argon Combat Hud by theripper93, which allows the user to have a solasta style hud for the token they are controlling.
Now when testing the blind death saves feature it works 100% perfectly on the sheet side, but Argon Combat Hud still displays the succeeded or failed death saves. Is it possible for you to fix this? That would be wonderful!
![image](https://github.com/malde/blind-death-saves/assets/43324035/af8bff88-6c17-41d6-9c9c-21fc45e12847)

**Comment by malde** [comment]
I'm not using it personally, so I've never investigated the possibility. Might be possible, but it will take some time to find out and I'm very short on time right now. Afraid it'll have to wait.
Will keep it on the list, though.

**Comment by malde** [comment]
Took me way longer than I thought it would, but managed to take a look at it and found a solution, will be fixed in the next release for dnd5e system 3.
