### ISSUE TITLE
Feature Request: Tidy 5e Sheets compatibility

### ISSUE THREAD

**Issue by kgar** [malde/blind-death-saves#4]
Hello, I am the Tidy 5e Sheets maintainer. We have mutual users who would love for us to establish compatibility between our modules.
I wanted to start a discussion about establishing compatibility and how we might accomplish it.

Is this something you'd be interested in?

**Comment by malde** [comment]
Hey there, last I checked, it is compatible. Unless you made some major changes to the sheet, since you took over as maintainer. I am no longer using it myself, but was before the official new dnd5e sheet.

**Comment by kgar** [comment]
As far as changes go, I did completely rewrite it from scratch and it now runs in svelte.
As of now, the roll behaviors from this module work as intended, but Blind Mode does not hide the death save total from the users in Tidy.
I can submit a PR if that is agreeable. I haven't looked at the code yet, but would you have a place for alternate sheets to have their behaviors wired up?

**Comment by malde** [comment]
Got it. The support is quite basic by just removing some elements from the dom. I'm also not very familiar with modern JS development myself.

I'm open to another approach,  be that API or hooks or whatever is the correct way to do this. 
Please feel free to suggest improvements or changes.

**Comment by malde** [comment]
@kgar I fixed the hiding of results in the tidy5e sheet, but am still open for suggestions on how to improve that. It's very much a "backend developer doing frontend"-fix.

**Comment by kgar** [comment]
That's awesome. Thank you for looking into that!

If you're interested, here are some suggested selector updates for those fields:

```js
      const tidyDeathSaveIconSuccess = $(html).find(
        ".death-saves .fa-check"
      );
      const tidyDeathSaveCounterSuccessAndFailure = $(html).find(
        `.death-saves .death-save-result`
      );
      const tidyDeathSaveIconFailure = $(html).find(
        ".death-saves .fa-times"
      );

      tidyDeathSaveIconSuccess.remove();
      tidyDeathSaveCounterSuccessAndFailure.remove();
      tidyDeathSaveIconFailure.remove();
```

Here's what I did:
- removed strict parent-child relationships so that if the structure ever changes, it will still look within the death-saves container
- removed specific element references, to account for if the elements themselves change in the future
- targeted death save results using the `.death-save-result` class

I have a modernized sheets project coming up soon, but I will do my best to keep these classes intact so that I don't re-break integration.

**Comment by malde** [comment]
Alright, thanks, I've gone ahead and applied those suggestions to be included in the next version.

I'm also fine with doing something akin to this pseudo-code:
```
if (sheet instanceof tidy5eSheet) {
  fireTidy5eHook(setHideDeathSaves(blind: bool))
}
```
however that might actually need to look, but that's the part where I'm totally out of my depths 😅

**Comment by kgar** [comment]
Thank you again for working with me on this. We've made some mutual users very happy 🫡
