### ISSUE TITLE
Feature Request: Pathfinder 2e compatibility

### ISSUE THREAD

**Issue by jpmiers** [malde/blind-death-saves#5]
I know its a big ask but I would love to use this functionality in pf2. Especially with it hiding the dying condition values as well. I know the system is quite different than D&D's so I understand if there is no intent to develop..

**Comment by malde** [comment]
I must admit, I'm entirely unfamiliar and don't play with the system itself. So indeed pretty unlikely.
I am however, open to contributions. Feel free to provide a PR. I also might look into it myself, but I don't expect that to be happening soon.
